version: "3.0"
services:
  nginx:
    image: nginxphptadeo
    ports:
      - "7001:80"
    volumes:
      - /home/mateo/Documentos/AdminRedes2024/Dockers/pagina:/usr/share/nginx/html
      - /home/mateo/Documentos/AdminRedes2024/Dockers/Conf/default.conf:/etc/nginx/conf.d/default.conf
